services:
  app:
    build: .
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      LAUNCHY_DRY_RUN: true # stop letter_opener from attempting to opening a browser
      BROWSER: /dev/null
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password

volumes:
  dbdata: